name: Run Node Daily

on:
  workflow_dispatch:
  schedule:
    - cron: 0 16 * * *
jobs:
  Run-Node:
    runs-on: ubuntu-latest
    env:
      ALIENWARE_REGION: secrets.REGION
      ALIENWARE_USERNAME: secrets.USERNAME
      ALIENWARE_PASSWORD: secrets.PASSWORD
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          check-latest: true
      - run: npm install
      - run: npm start
